version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"   # 컨테이너의 8080 포트를 호스트의 8080 포트로 매핑
    environment:
      - SPRING_PROFILES_ACTIVE=default   # 애플리케이션 프로필을 prod로 설정
    depends_on:
      #- mysql-container  # db 컨테이너가 실행된 후에만 app이 실행되도록 설정
      mysql-container:
        condition: service_healthy
    networks:
      - app-network  # 네트워크 설정 추가

  mysql-container:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: admin    # MySQL root 사용자 비밀번호 설정
      MYSQL_DATABASE: review_db       # 기본 데이터베이스 생성
    ports:
      - "3306:3306"  # MySQL의 기본 포트 3306을 호스트의 3306 포트로 매핑
    networks:
      - app-network  # 네트워크 설정 추가
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  app-network:
    driver: bridge  # 네트워크 드라이버 지정
