version: '3.8'

services:
  mysql:
    image: mysql:8
    restart: always
    container_name: local-mysql
    ports:
      - "33009:3306"
    environment:
      MYSQL_DATABASE: kafka_reviews
      MYSQL_USER: kafka
      MYSQL_PASSWORD: kafka
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
